version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - ollama
    ports:
      - "8000:8000" # Adjust the port according to your backend configuration
    environment:
      - PYTHONPATH=/backend # Set the PYTHONPATH to the /app directory

  ollama:
    image: ollama/ollama
    runtime: nvidia
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    # command: sh -c "ollama pull llama3.1:8b && ollama run llama3.1:8b"
    # entrypoint: ["ollama", "pull", "llama3.1:8b"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

volumes:
  ollama:
