version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    env_file:
      - .env

  ollama:
    image: ollama/ollama
    runtime: nvidia
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "11434:11434"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    env_file:
      - .env

volumes:
  ollama:
