version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - LOCAL_LLM_HOST=ollama
      - LOCAL_LLM_PORT=11434
    env_file:
      - .env

  ollama:
    image: ollama/ollama
    runtime: nvidia
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "11434:11434"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "sh", "-c", "ls /tmp/ollama_pulled"]
      interval: 5s
      timeout: 3s
      retries: 200

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
    ports:
      - "80:7860"
    environment:
      - HOST=backend
      - PORT=8000
    env_file:
      - .env
volumes:
  ollama:
